- name: Deploy frontend and backend containers from GitHub
  hosts: all
  become: yes

  vars:
    repo_url: "https://github.com/alfarmur/2nd10WeeksofCloudOps-main.git"
    app_path: "/root/ramya/"
    frontend_image: "frontend-app:latest"
    backend_image: "backend-app:latest"
    rds_host: "database-1.cjkookymada4.us-east-1.rds.amazonaws.com"
    rds_user: "admin"
    rds_password: "irumporaI"
    rds_port: "3306"

  roles:
    - common
    - gitclone
    - frontend
    - backend

